const db = require("../db/database");
const { v4: uuidv4 } = require("uuid");

//generating a newapi key
exports.generateKey = (req, res) => {
  const key = uuidv4();
  const userId = req.user.id;

  db.run(
    `INSERT INTO api_keys (key, user_id) VALUES (?, ?)`,
    [key, userId],
    function (err) {
      if (err) return res.status(500).json({ error: "Error generating key" });
      res.status(201).json({ key });
    }
  );
};

//retrieving the generated apikeys by the user
exports.getKeys = (req, res) => {
  const userId = req.user.id;
  db.all(`SELECT * FROM api_keys WHERE user_id = ?`, [userId], (err, keys) => {
    if (err) return res.status(500).json({ error: "Error retrieving keys" });
    res.json(keys);
  });
};

//deleting an existing apikey generated by the user
exports.deleteKey = (req, res) => {
  const { id } = req.params;
  const userId = req.user.id;

  db.run(
    `DELETE FROM api_keys WHERE id = ? AND user_id = ?`,
    [id, userId],
    function (err) {
      if (err || this.changes === 0)
        return res.status(400).json({ error: "Key not found or unauthorized" });
      res.json({ message: "Key deleted" });
    }
  );
};
